language: java
before_install:
  sudo pip install codecov
after_success:
    codecov
jdk:
  - oraclejdk7
before_script:
  - mysql -e 'create database mamute_test;'
install: ""
notifications:
    email:
        recipients:
            - khajavi@gmail.com
        on_success: change
        on_failure: always