version: '2'
services:
  webserver:
    build:
      context: "./Nginx"
      args:
        - MAIN_SITE_URL=${MAIN_SITE_URL}
        - TABAYE_URL=${TABAYE_URL}
    environment:
      - MAIN_SITE_URL=${MAIN_SITE_URL}
      - TABAYE_URL=${TABAYE_URL}
    ports:
      - "80:80"
      - "443:443"
    restart: always
    mem_limit: 128MB
    links:
      # These names are used inside ./Nginx/conf.d/*.conf
      - shomabegoo:shomabegoo
      - tabaye:tabaye

  shomabegoo:
    build:
      context: ./Shomabegoo/
      args:
        - DB=${MYSQL_DATABASE}
        - USER=${MYSQL_USER}
        - PASSWORD=${MYSQL_PASSWORD}
        - MAIN_SITE_URL=${MAIN_SITE_URL}
        - VRAPTOR_SIMPLEMAIL_MAIN_PASSWORD=${VRAPTOR_SIMPLEMAIL_MAIN_PASSWORD}
        - VRAPTOR_SIMPLEMAIL_SEND_REAL_EMAIL=${VRAPTOR_SIMPLEMAIL_SEND_REAL_EMAIL}
        - FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    restart: always
    mem_limit: 512m
    links:
      - db

  tabaye:
    build:
      context: ./Tabaye/
      args:
        - DB=${MYSQL_DATABASE}
        - USER=${MYSQL_USER}
        - PASSWORD=${MYSQL_PASSWORD}
        - TABAYE_URL=${TABAYE_URL}
        - VRAPTOR_SIMPLEMAIL_MAIN_PASSWORD=${VRAPTOR_SIMPLEMAIL_MAIN_PASSWORD}
        - VRAPTOR_SIMPLEMAIL_SEND_REAL_EMAIL=${VRAPTOR_SIMPLEMAIL_SEND_REAL_EMAIL}
        - FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    restart: always
    mem_limit: 512m
    links:
      - db

  db:
    image: mysql:latest
    restart: always
    volumes:
      # Used to save the database locally
      - ./MySQL/database:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MAIN_SITE_URL=${MAIN_SITE_URL}
      - TABAYE_URL=${TABAYE_URL}
