webserver:
  image: nginx:1.9
  ports:
    - "80:80"
    - "443:443"
  restart: always
  mem_limit: 128MB
  volumes:
    - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./Nginx/ssl/:/etc/nginx/ssl/:ro
    - ./Nginx/conf.d/:/etc/nginx/conf.d/:ro
  links:
    # This name is used inside ./Nginx/conf.d/test.conf
    - shomabegoo:shomabegoo
    - tabaye:tabaye


shomabegoo:
  # You'll find the Mamute version in ./Shomabegoo/Dockerfile
  build: ./Shomabegoo/
  restart: always
  mem_limit: 512m
  links:
    - db

tabaye:
  # You'll find the Mamute version in ./Tabaye/Dockerfile
  build: ./Tabaye/
  restart: always
  mem_limit: 512m
  links:
    - db

db:
  # MySQL 5.7.5 and above produces exceptions in Mamute
  image: mysql:latest
  restart: always
  volumes:
    # Used to save the database locally
    - ./MySQL/database:/var/lib/mysql:rw
  # On change remember to edit these variables also in file ./Mamute/Dockerfile
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
