mysql:
  image: mysql:latest
  ports:
    - "3307:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=1
    - MYSQL_DATABASE=shomabegoo_db
    - MYSQL_USER=mamute
    - MYSQL_PASSWORD=1
  volumes:
    - ./data:/docker-entrypoint-initdb.d
    - ./MySQL/database:/var/lib/mysql:rw
